### ISSUE TITLE
Subscriber count mismatch

### ISSUE THREAD

**Issue by alikuru** [andris9/mailtrain#83]
I see a lower subscriber count for a list I created when I check my lists page. When I check the database with the query below, I see 28223 subscribers are available on my list:

    SELECT email FROM subscription__1 WHERE status=1

However, listing page shows only 26300 subscribers on the list. This happened after I updated it with a small set (approx. 3500) of subscribers.

Any ideas on the reason behind the discrepancy?

**Comment by andris9** [comment]
No idea, seems to be a bug. Was the subscribers count previously correct? And then you imported a list from CSV and it messed up the counter?

**Comment by alikuru** [comment]
> Was the subscribers count previously correct? And then you imported a list from CSV and it messed up the counter?

I believe so.

If there is anything I can do to debug the issue and create a bug report, please do tell. I'll happily help out in any way I can.

**Comment by andris9** [comment]
When importing did you only use the "subscribe" option or did you also imported a list with "unsubscribed" addresses?

**Comment by alikuru** [comment]
Did both actually.

I ran a test campaign to a list which I wasn't sure about its hygiene. Then exported bounces and successful sends from the database to two different CSV files with these queries:

Sends

    SELECT email, first_name, last_name, FROM subscription__3 WHERE status=1 ORDER BY email, first_name, last_name

Bounces

    SELECT email, first_name, last_name, FROM subscription__3 WHERE status=3 ORDER BY email, first_name, last_name

After that, I imported sends to my main list with "subscribe", then bounces with "unsubscribe" option.

**Comment by andris9** [comment]
Ok, I think there is a bug in importing unsubscribed users where the count of subscribers is decremented too much

**Comment by andris9** [comment]
I fixed the bug that decremented subscribers count when adding new unsubscribed users

**Comment by alikuru** [comment]
Great, thanks for the update.

My lists subscriber count still shows the same -missing- amount of subscribers though, do I need to take any extra action to fix that?

I already did a `git pull origin master && npm install --production` after your last commit.

**Comment by andris9** [comment]
Yes, this does not fix the already invalid counter, it only fixes the behavior. You can fix your counter manually, check the `lists` table in MySQL and set the `subscribers` field to the actual count of yous subscribed subscribers

**Comment by alikuru** [comment]
OK, fixed that manually. Everything seems fine now :8ball:
